#!/bin/sh /etc/rc.common
# shellcheck shell=dash
# shellcheck disable=SC2034,SC2154 # START/USE_PROCD are read by rc.common, $initscript is set by it

START=96
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/podkop-sub daemon
    procd_set_param respawn
    # the daemon finishes its iteration before exiting, so an apply is never cut in half
    procd_set_param term_timeout 30
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_config_trigger "config.change" "podkop-sub" "$initscript" restart
}
